#!/usr/bin/env python3
"""
Extract all filter coefficients from the ITU-T STL C reference and generate
Rust source files with the coefficient tables.

The STL C source (copyrighted, ITU-T GPL) is NOT part of this repository. This
script runs against a manual clone of the reference code (see scripts/clone_stl.sh)
and only extracts the numeric coefficient values for porting.
"""

import pathlib
import re

BASE = pathlib.Path(__file__).resolve().parents[1]
STL_DIR = BASE / "tmp" / "_stl_extract" / "src"

F24 = 0x00800000  # float scaling constant used in STL
F16 = 32768.0  # float scaling constant used in STL


def main() -> None:
    out = []
    out.append("// SPDX-License-Identifier: MIT")
    out.append("// Copyright 2026, Jan.Reimes")
    out.append("// Auto-generated by scripts/extract_stl_coefficients.py from ITU-T G.191 STL")
    out.append("// reference coefficient tables (values normalized to unit range).")
    out.append("// DO NOT EDIT BY HAND - regenerate with: python scripts/extract_stl_coefficients.py")
    out.append("")

    # ---------------- FIR ----------------
    out.append("pub mod fir {")
    flat = (STL_DIR / "fir" / "fir-flat.c").read_text(encoding="utf-8", errors="replace")
    irs = (STL_DIR / "fir" / "fir-irs.c").read_text(encoding="utf-8", errors="replace")
    lp = (STL_DIR / "fir" / "fir-LP.c").read_text(encoding="utf-8", errors="replace")

    fir_specs = [
        ("HQ_DOWN_2_TO_1", "h02", "f24", "High-quality 2:1 downsampling FIR, 16 kHz"),
        ("HQ_DOWN_3_TO_1", "h03", "f24", "High-quality 3:1 downsampling FIR, 16 kHz"),
        ("FLAT_BAND_PASS", "flat_coef", "f16", "Flat band-pass FIR, 8 kHz"),
        ("IRS8", "h0IRS8", "f24", "IRS receive weighting, 8 kHz"),
        ("IRS16", "h0IRS16", "f24", "IRS receive weighting, 16 kHz"),
        ("MOD_IRS16", "mod_irs16_coef", "f16", "Modified IRS send weighting, 16 kHz"),
        ("MOD_IRS48", "mod_irs48_coef", "f16", "Modified IRS send weighting, 48 kHz"),
        ("LP1P5_48K", "LP1p5_48khz_coeff", "float", "Low-pass 1.5 kHz, 48 kHz"),
        ("LP35_48K", "LP35_48khz_coeff", "float", "Low-pass 3.5 kHz, 48 kHz"),
        ("LP7_48K", "LP7_48khz_coeff", "float", "Low-pass 7 kHz, 48 kHz"),
        ("LP10_48K", "LP10_48khz_coeff", "float", "Low-pass 10 kHz, 48 kHz"),
        ("LP12_48K", "LP12_48khz_coeff", "float", "Low-pass 12 kHz, 48 kHz"),
        ("LP14_48K", "LP14_48khz_coeff", "float", "Low-pass 14 kHz, 48 kHz"),
        ("LP20_48K", "LP20_48khz_coeff", "float", "Low-pass 20 kHz, 48 kHz"),
    ]
    for const, cname, scale, doc in fir_specs:
        src = flat if cname in ("h02", "h03", "flat_coef") else (irs if cname.startswith(("h0IRS", "mod_irs")) else lp)
        vals = extract_1d(src, cname, scale)
        if vals is None:
            print(f"WARN: FIR {cname} not found")
            continue
        out.append(rust_1d(const, vals, doc))
        out.append("")
    out.append("}")
    out.append("")

    # ---------------- IIR ----------------
    out.append("pub mod iir {")
    g712 = (STL_DIR / "iir" / "iir-g712.c").read_text(encoding="utf-8", errors="replace")
    iflat = (STL_DIR / "iir" / "iir-flat.c").read_text(encoding="utf-8", errors="replace")

    b16 = extract_2d(g712, "b_16khz", "f24")
    c16 = extract_2d(g712, "c_16khz", "f24")
    if b16 and c16:
        out.append("    /// G.712 PCM weighting, parallel form, 16 kHz")
        out.append("    pub const G712_16K_K: f64 = -0.620901;")
        out.append(rust_2d("G712_16K_B", b16, "Numerator b[N][3]"))
        out.append("")
        out.append(rust_2d("G712_16K_C", c16, "Denominator c[N][2]"))
        out.append("")

    # iir-flat.c: cascade-form LP for 3:1 / 1:3 rate change (same coeffs, different gain)
    a_iir = extract_2d(iflat, "a_iir_3_1", "float")
    b_iir = extract_2d(iflat, "b_iir_3_1", "float")
    if a_iir and b_iir:
        out.append("    /// Cascade LP (numerator a / denominator b), 3:1 down and 1:3 up, 16 kHz")
        out.append("    pub const CASC_LP_GAIN_3TO1: f64 = 2.552013334e-04;")
        out.append("    pub const CASC_LP_GAIN_1TO3: f64 = 3.0 * 2.552013334e-04;")
        out.append(rust_2d("CASC_LP_A", a_iir, "Numerator a[N][2] (feedforward)"))
        out.append("")
        out.append(rust_2d("CASC_LP_B", b_iir, "Denominator b[N][2] (feedback)"))
        out.append("")

    # iir-dir.c: direct-form IIR filters
    idir = (STL_DIR / "iir" / "iir-dir.c").read_text(encoding="utf-8", errors="replace")
    a_lp = extract_1d(idir, "a_lp_3_1", "float")
    b_lp = extract_1d(idir, "b_lp_3_1", "float")
    if a_lp and b_lp:
        out.append("    /// Direct-form LP 3:1 downsampling, 16 kHz (a = zeros, b = poles)")
        out.append("    pub const DIR_LP_3TO1_GAIN: f64 = 1.0;")
        out.append(rust_1d("DIR_LP_3TO1_A", a_lp, "Numerator (zeros) a[N]"))
        out.append("")
        out.append(rust_1d("DIR_LP_3TO1_B", b_lp, "Denominator (poles) b[N]"))
        out.append("")

    a_dc = extract_1d(idir, "a_dc", "float")
    b_dc = extract_1d(idir, "b_dc", "float")
    if a_dc and b_dc:
        out.append("    /// Direct-form DC removal, 1:1, 48 kHz (a = zeros, b = poles)")
        out.append("    pub const DIR_DC_GAIN: f64 = 1.0;")
        out.append(rust_1d("DIR_DC_A", a_dc, "Numerator (zeros) a[N]"))
        out.append("")
        out.append(rust_1d("DIR_DC_B", b_dc, "Denominator (poles) b[N]"))
        out.append("")
    out.append("}")

    dest = BASE / "src" / "g191_filter" / "src" / "coeffs_generated.rs"
    dest.write_text("\n".join(out) + "\n", encoding="utf-8")
    print(f"Wrote {dest} ({len(out)} lines)")


def extract_1d(text: str, name: str, scale: str) -> list[float] | None:
    """Extract a 1D static float array by name."""
    m = re.search(rf"static\s+float\s+{name}\s*\[\w+\]\s*=\s*\{{(.*?)\}};", text, re.DOTALL)
    if not m:
        return None
    body = strip_comments(m.group(1))
    if scale in ("f24", "f16"):
        return parse_f24(body)
    return parse_float(body)


def parse_f24(text: str) -> list[float]:
    """Parse f24/f16-scaled integer coefficients."""
    values = []
    for m in re.finditer(r"(-?\d+\.?\d*)\s*/\s*(f24|f16)", text):
        num = float(m.group(1))
        scale = F24 if m.group(2) == "f24" else F16
        values.append(num / scale)
    return values


def extract_2d(text: str, name: str, scale: str, occurrence: int = -1) -> list[list[float]] | None:
    """Extract a 2D static float array by name (rows of fixed length).
    occurrence=-1 picks the last definition (C allows redefinition in separate scopes).
    """
    matches = list(re.finditer(rf"static\s+float\s+{name}\s*\[\w+\]\s*\[\w+\]\s*=\s*\{{(.*?)\}};", text, re.DOTALL))
    if not matches:
        return None
    m = matches[occurrence]
    body = strip_comments(m.group(1))
    rows = re.findall(r"\{([^}]*)\}", body)
    if not rows:
        return None
    return [parse_f24_row(r) for r in rows] if scale == "f24" else [parse_float(r) for r in rows]


def strip_comments(text: str) -> str:
    text = re.sub(r"/\*.*?\*/", "", text, flags=re.DOTALL)
    text = re.sub(r"//[^\n]*", "", text)
    return text


def parse_f24_row(text: str) -> list[float]:
    """Parse one row of f24-scaled coefficients, keeping bare values (e.g. 0.)."""
    values = []
    # Split elements on commas outside braces; each is either '0.' or 'N. / f24'
    for elem in text.split(","):
        elem = elem.strip()
        if not elem:
            continue
        m = re.match(r"^(-?\d+\.?\d*)\s*/\s*(f24|f16)$", elem)
        if m:
            scale = F24 if m.group(2) == "f24" else F16
            values.append(float(m.group(1)) / scale)
        else:
            # Bare numeric literal (e.g. '0.'), or 'F24' macro reference
            m2 = re.match(r"^-?\d+\.?\d*$", elem)
            if m2:
                values.append(float(elem))
    return values


def parse_float(text: str) -> list[float]:
    """Parse floating-point coefficients in scientific or decimal notation."""
    values = []
    for elem in text.split(","):
        elem = elem.strip()
        if not elem:
            continue
        # Match scientific notation (e.g., 1.2e-3) OR decimal numbers (e.g., 1.0, 0.)
        m = re.match(r"^(-?\d+\.?\d*(?:e[+-]?\d+)?)$", elem, re.IGNORECASE)
        if m:
            values.append(float(m.group(1)))
        else:
            # If element doesn't match either pattern, try to parse it directly
            # This handles cases like "1." (integer) or other valid numbers
            try:
                values.append(float(elem))
            except ValueError:
                pass
    return values


def rust_1d(name: str, values: list[float], doc: str) -> str:
    lines = [f"    /// {doc}", f"    pub const {name}: &[f64] = &["]
    for i in range(0, len(values), 6):
        row = ", ".join(f"{v:.17e}" for v in values[i : i + 6])
        lines.append(f"        {row},")
    lines.append("    ];")
    return "\n".join(lines)


def rust_2d(name: str, values: list[list[float]], doc: str) -> str:
    lines = [f"    /// {doc}", f"    pub const {name}: &[[f64; {len(values[0])}]] = &["]
    for row in values:
        lines.append(f"        [{', '.join(f'{v:.17e}' for v in row)}],")
    lines.append("    ];")
    return "\n".join(lines)


if __name__ == "__main__":
    main()
